export type UserRole = 'student' | 'creator' | 'admin';

export interface User {
  id: string;
  uid: string; // Immutable, e.g., RML-A9B8C7D6
  email: string;
  username: string;
  fullName: string;
  role: UserRole;
  age?: number;
  country?: string;
  countryCode?: string;
  avatarUrl?: string;
  isEmailVerified: boolean;
  isSuspended: boolean;
  suspensionReason?: string;
  suspensionDuration?: string;
  missedExamsCount: number;
  academicRestricted: boolean;
  createdAt: string;
  updatedAt: string;
  level: number;
  xp: number;
  learningStreak: number;
}

export interface StudentProfile {
  uid: string;
  fullName: string;
  username: string;
  email: string;
  country: string;
  countryCode: string;
  age?: number;
  avatarUrl?: string;
  bio?: string;
  targetSubjects: string[];
  learningGoals: string[];
  level: number;
  xp: number;
  nextLevelXp: number;
  learningStreak: number;
}

export interface CreatorProfile {
  uid: string;
  fullName: string;
  username: string;
  email: string;
  avatarUrl?: string;
  bio?: string;
  specialty?: string;
  website?: string;
  brandKit?: {
    primaryColor: string;
    secondaryColor: string;
    brandFont: string;
    brandName: string;
  };
}

export interface AuthResponse {
  token: string;
  user: User;
  message?: string;
}

export interface AIMessage {
  id: string;
  conversationId: string;
  sender: 'student' | 'tutor';
  text: string;
  imageUrl?: string;
  audioUrl?: string;
  timestamp: string;
  isStreaming?: boolean;
}

export interface AIConversation {
  id: string;
  studentUid: string;
  title: string;
  subject?: string;
  createdAt: string;
  updatedAt: string;
  summary?: string;
  messages: AIMessage[];
}

export interface AIMemory {
  id: string;
  studentUid: string;
  category: 'subject' | 'goal' | 'weakness' | 'strength' | 'preference' | 'class';
  fact: string;
  recordedAt: string;
  confidenceScore: number;
}

export interface ScheduledClass {
  id: string;
  studentUid: string;
  subject: string;
  topic: string;
  days: string[]; // e.g., ["Monday", "Wednesday"]
  time: string; // e.g., "15:00"
  durationMinutes: number;
  learningGoal: string;
  status: 'active' | 'completed' | 'cancelled';
  nextSessionDate: string;
  createdAt: string;
}

export interface Question {
  id: string;
  type: 'multiple_choice' | 'short_answer' | 'written';
  question: string;
  options?: string[];
  correctAnswer?: string;
  explanation?: string;
  points: number;
}

export interface Exam {
  id: string;
  title: string;
  course: string;
  subject: string;
  description: string;
  durationMinutes: number;
  passingScore: number;
  totalPoints: number;
  questions: Question[];
  createdAt: string;
  isAutoGenerated?: boolean;
}

export interface ExamAttempt {
  id: string;
  examId: string;
  examTitle: string;
  studentUid: string;
  answers: Record<string, string>;
  score?: number;
  totalPoints: number;
  percentage?: number;
  passingScore: number;
  status: 'in_progress' | 'submitted' | 'graded' | 'passed' | 'failed' | 'missed';
  startTime: string;
  submissionTime?: string;
  attemptNumber: number;
  tabSwitches: number;
  interruptionFlags: string[];
  feedback?: string;
  xpEarned?: number;
}

export interface NotificationItem {
  id: string;
  userUid: string;
  type:
    | 'class_reminder'
    | 'exam_reminder'
    | 'exam_result'
    | 'level_up'
    | 'xp_earned'
    | 'new_assignment'
    | 'tutor_alert'
    | 'account_alert'
    | 'security_alert';
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
  actionUrl?: string;
}

export interface CreatorGeneration {
  id: string;
  creatorUid: string;
  prompt: string;
  style: string;
  aspectRatio: string;
  imageUrl: string;
  createdAt: string;
  downloadCount: number;
}

export interface AdminStats {
  totalUsers: number;
  totalStudents: number;
  totalCreators: number;
  activeUsers: number;
  suspendedUsers: number;
  recentRegistrations: User[];
  totalExams: number;
  totalExamAttempts: number;
  totalScheduledClasses: number;
  totalImageGenerations: number;
  aiUsageStats: {
    tutorQueries: number;
    imageGenerations: number;
    averageResponseTimeMs: number;
  };
}

export interface AssignmentSolutionStep {
  stepNumber: number;
  title: string;
  description: string;
  formulaOrWorking?: string;
}

export interface AssignmentSolution {
  id: string;
  studentUid: string;
  subject?: string;
  title: string;
  questionText: string;
  keyConcepts: string[];
  stepByStepSolution: AssignmentSolutionStep[];
  finalAnswer: string;
  verificationTips: string;
  rawExplanation?: string;
  imageUrl?: string;
  createdAt: string;
}

export interface CommunityJoinRequest {
  uid: string;
  fullName: string;
  username: string;
  role: UserRole;
  requestedAt: string;
  status: 'pending' | 'approved' | 'rejected';
}

export interface Community {
  id: string;
  name: string;
  description: string;
  icon?: string;
  bannerGradient?: string;
  isOfficial: boolean; // Managed by Remly Admin
  createdBy: string; // UID of creator
  creatorName: string;
  admins: string[]; // array of UIDs
  members: string[]; // array of UIDs
  isPublic: boolean; // true = visible to all & can request to join; false = private/hidden (only visible if added by UID)
  joinRequests: CommunityJoinRequest[];
  rules: string[];
  tags: string[];
  createdAt: string;
  updatedAt?: string;
}

export interface CommunityMessage {
  id: string;
  communityId: string;
  senderId: string; // UID or 'remly-ai'
  senderName: string;
  senderRole: 'student' | 'creator' | 'admin' | 'ai';
  senderAvatar?: string;
  content: string;
  type: 'text' | 'image' | 'voice' | 'sticker' | 'system';
  mediaUrl?: string; // image data URL or voice note audio URL/base64
  audioDuration?: number; // duration in seconds for voice notes
  stickerId?: string;
  reactions: Record<string, string[]>; // emoji -> array of user UIDs
  mentions?: string[]; // e.g. ['@remly', '@wisdom']
  createdAt: string;
  replyTo?: {
    id: string;
    senderName: string;
    content: string;
  };
}
